### ISSUE TITLE
社内 git 勉強会〜 ﾄﾞﾝﾄﾞﾝﾊﾟﾌﾊﾟﾌ

### ISSUE THREAD

**Issue by matsubara0507** [matsubara0507/learn-you-a-git-for-great-good#1]
をいい感じにするためにメモメモ

- [x] コンテンツを洗い出す
- [ ] スライド
- [ ] グラフィカルに

**Comment by neglect-yp** [comment]
HTMLとかJSみたいなデザイナーが触りそうなものをベースにするか、
Markdown、もっといえばただのテキストファイルみたいな知識ゼロでも触れるほうがいいのか

**Comment by kiwiyuki** [comment]
CLIでやるときは`cd`, `ls`なども教える/覚えるという点があります

**Comment by mitsu9** [comment]
若干の事前準備必要そう？
やってきてもらうか中でやるか

必要そうな準備
- install git
- create GitHub account
- お好きなエディタ

**Comment by matsubara0507** [comment]
> HTMLとかJSみたいなデザイナーが触りそうなものをベースにするか、

そうそれ 

> CLIでやるときはcd, lsなども教える/覚えるという点があります

`cd` `ls` なるほど、普通のやつか
CLI or GUI はお好きなのを使ってもらおうかと、どれもだいたいわかるし、人数少なそうだから個別に対応できそう

**Comment by matsubara0507** [comment]
事前準備はね、参加者がどれくらい時間取れそうかによる
1日(19:00~22:00)でやるなら必要だし、2,3日に分けれそうなら事前準備はいらないかなと

**Comment by matsubara0507** [comment]
試しに part1 を書いて見た
https://github.com/matsubara0507/learn-you-a-git-for-great-good/blob/master/docs/part1.md

CLI なのは暫定的。
この内容をベースに図表などを足してスライドを作る。

### 加筆したい内容

- コミットメッセージの書き方
- リビジョン

### きになるところ

- いくつかの文言（段階とかモノとか）

**Comment by matsubara0507** [comment]
part0-4 までとりあえず書いた（細かいコマンドなどは抜けてる）
https://github.com/matsubara0507/learn-you-a-git-for-great-good/tree/master/docs

**Comment by matsubara0507** [comment]
## やってみて

- 想像以上に CLI は受け入れられない
- 結局 SourceTree でやった
- CLI 抜きだと、ファイル作ったりディレクトリ作ったりよくわからん
     - デスクトップと言う存在を失念
- blob/commit/repository のようなモノから入るのは割と受け入れられた
- ブランチ is 何？と言うのは初めの方にあった

**Comment by matsubara0507** [comment]
完
